spring.application.name=tech_go_api
# --- DEBUG CACHING/REDIS ---
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Tech_go_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret=sdkjhfgkjdfhbgvkjsbdvkjbfvburiuvnbsdjlvniwjuenv652654
jwt.access.token.duration.minutes=15
jwt.refresh.token.duration.days=7

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=techgo

# MinIO
minio.url=http://localhost:9000/
minio.endpoint=http://localhost:9000/
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucketName=techgo
minio.port=9000
minio.use-ssl=false
