spring.application.name=tech_go_api
# --- DEBUG CACHING/REDIS ---
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG


# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access.token.duration.minutes=${JWT_ACCESS_TOKEN_DURATION_MINUTES}
jwt.refresh.token.duration.days=${JWT_REFRESH_TOKEN_DURATION_DAYS}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}


spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=techgo

# MinIO
minio.url=${MINIO_URL}
minio.endpoint=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucketName=${MINIO_BUCKET}
minio.port=9000
minio.use-ssl=false
