package com.example.tech_go_api.domain.staff;

public enum Permission {
    ATLETAS_VER,
    ATLETAS_MATRICULAR,
    ATLETAS_EDITAR,
    ATLETAS_INATIVAR,
    ATLETAS_REATIVAR,
    ATLETAS_EXCLUIR_PERMANENTE,
    ATLETAS_IMPRIMIR,

    RESPONSAVEIS_VER,
    RESPONSAVEIS_CRIAR,
    RESPONSAVEIS_EDITAR,
    RESPONSAVEIS_EXCLUIR,

    PAGAMENTOS_VER,
    PAGAMENTOS_LANCAR,
    PAGAMENTOS_DAR_BAIXA,
    PAGAMENTOS_EDITAR,
    PAGAMENTOS_MARCAR_PENDENTE,
    PAGAMENTOS_EXCLUIR,

    JOGOS_VER,
    JOGOS_CRIAR,
    JOGOS_EDITAR,
    JOGOS_FAZER_CHAMADA,
    JOGOS_EXCLUIR,

    AULAS_VER_GRUPOS,
    AULAS_CRIAR_GRUPO,
    AULAS_EDITAR_GRUPO,
    AULAS_EXCLUIR_GRUPO,
    AULAS_REGISTRAR_AULA,
    AULAS_FAZER_CHAMADA,
    AULAS_EDITAR_CHAMADA_PASSADA,
    AULAS_EXCLUIR_SESSAO,
    AULAS_GERAR_RELATORIO,
}
